### PR TITLE
Pacifico update / first PR

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @EbenSorkin, hi @Black-sage,

I exported the fonts with gftools and reviewed them. All looks great, I just wanted to check with you some details I noticed:
Some of connections look a bit weird in the new version, and there is a big gap in the ldot. Is it intentional?
In any case, if you could first merge this PR, it would be great! I'll pull your modifications then if there are some.
Thank you! :)

**OLD**
Screenshot 2023-12-06 at 15 09 16

**NEW**
Screenshot 2023-12-06 at 15 09 26

____________

**OLD**
Screenshot 2023-12-06 at 15 09 57

**NEW**
Screenshot 2023-12-06 at 15 10 04

### CODE REVIEW

**Comment by Black-sage** [comment]
Hi @emmamarichal @EbenSorkin , I made updates to the file. Everything should be good now, could you please take a look at the file?

**Comment by EbenSorkin** [comment]
Rafael, do you know how to merge a pull request?

**Comment by emmamarichal** [comment]
Hi @Black-sage,
Thank you! I added some few last modifications, you can now merge the PR -> "Merge Pull Request"

Cheers!

**Comment by Black-sage** [comment]
@emmamarichal The merge is done, and you can proceed with the onboarding

**Comment by emmamarichal** [comment]
@Black-sage Excellent, thank you! I'll do this tomorrow :)

**Pull request merged**
